#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: #@ data.values.namespace
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
data:
  #@ if len(data.values.grafana.username) == 0:
  #@  assert.fail("grafana.username cannot be empty")
  #@ end
  #@ if len(data.values.grafana.password) == 0:
  #@  assert.fail("grafana.password cannot be empty")
  #@ end
  admin-user: #@ base64.encode(data.values.grafana.username)
  admin-password: #@ base64.encode(data.values.grafana.password)
