---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.9.0

directories:
- path: vendor
  contents:
  - path: github.com/JamesClonk/postgres-k8s
    git:
      url: https://github.com/JamesClonk/postgres-k8s
      ref: 8166bc22a5612943ff96aa9a7924809794fba518
    includePaths:
    - "templates/**/*"
- path: postgres/templates/standalone
  contents:
  - path: .
    directory:
      path: vendor/github.com/JamesClonk/postgres-k8s/templates/standalone
    excludePaths:
    - LICENSE
