---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.10.0

directories:
- path: vendor/github.com/helm/charts
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: f42e3c4b827d8ee54cce31de2619631bfa484610 # chart versions: prometheus/11.12.0, grafana/5.5.5
    includePaths:
    - stable/grafana/**/*
    - stable/prometheus/**/*
    - stable/kube-state-metrics/**/*
- path: prometheus/build/charts/kube-state-metrics
  contents:
  - path: .
    directory:
      path: vendor/github.com/helm/charts/stable/kube-state-metrics
    excludePaths:
    - LICENSE
- path: prometheus/build/charts/prometheus
  contents:
  - path: .
    directory:
      path: vendor/github.com/helm/charts/stable/prometheus
    excludePaths:
    - LICENSE
- path: grafana/build/charts/grafana
  contents:
  - path: .
    directory:
      path: vendor/github.com/helm/charts/stable/grafana
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/loki
  contents:
  - path: .
    git:
      url: https://github.com/grafana/loki
      ref: 00f494e536654b9c16bb2a27f7d43b1ca9752217 # chart versions: loki/0.31.0, promtail/0.24.0
    includePaths:
    - production/helm/loki/**/*
    - production/helm/promtail/**/*
- path: loki/build/charts/loki
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/loki/production/helm/loki
    excludePaths:
    - LICENSE
- path: loki/build/charts/promtail
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/loki/production/helm/promtail
    excludePaths:
    - LICENSE

- path: vendor/github.com/JamesClonk/postgres-k8s
  contents:
  - path: .
    git:
      url: https://github.com/JamesClonk/postgres-k8s
      ref: a14617f0208c6731977868cc7fe15e6b27f7a0ec
    includePaths:
    - "templates/**/*"
- path: postgres/templates
  contents:
  - path: .
    directory:
      path: vendor/github.com/JamesClonk/postgres-k8s/templates/postgresql
    excludePaths:
    - LICENSE
