---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.9.0

directories:
- path: vendor/github.com/helm/charts
  contents:
  - path: .
    git:
      url: https://github.com/helm/charts
      ref: f42e3c4b827d8ee54cce31de2619631bfa484610 # version: prometheus/11.12.0
    includePaths:
    - stable/prometheus/**/*
    - stable/kube-state-metrics/**/*
- path: prometheus/build/charts/kube-state-metrics
  contents:
  - path: .
    directory:
      path: vendor/github.com/helm/charts/stable/kube-state-metrics
    excludePaths:
    - LICENSE
- path: prometheus/build/charts/prometheus
  contents:
  - path: .
    directory:
      path: vendor/github.com/helm/charts/stable/prometheus
    excludePaths:
    - LICENSE

- path: vendor/github.com/JamesClonk/postgres-k8s
  contents:
  - path: .
    git:
      url: https://github.com/JamesClonk/postgres-k8s
      ref: a14617f0208c6731977868cc7fe15e6b27f7a0ec
    includePaths:
    - "templates/**/*"
- path: postgres/templates
  contents:
  - path: .
    directory:
      path: vendor/github.com/JamesClonk/postgres-k8s/templates/postgresql
    excludePaths:
    - LICENSE
