apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cf-env
spec:
  rules:
  - host: cf-env.${KUBE_DOMAIN}
    http:
      paths:
      - backend:
          serviceName: cf-env
          servicePort: 80
