#@ load("@ytt:data", "data")

#@ def labels():
  component: prometheus-msteams
  app: prometheus
  release: prometheus
#@ end

#@ def labelSelector():
  matchExpressions:
  - key: component
    operator: In
    values:
    - prometheus-msteams
  - key: app
    operator: In
    values:
    - prometheus
  - key: release
    operator: In
    values:
    - prometheus
#@ end

#@ def podAntiAffinity():
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector: #@ labelSelector()
#@ end
