#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app + "-config"
  namespace: #@ data.values.namespace
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
#@yaml/text-templated-strings
stringData:
  #@ if len(data.values.msteams.webhook_url) == 0:
  #@  assert.fail("msteams.webhook_url cannot be empty")
  #@ end
  connectors.yml: |
    connectors:
    - msteams: (@= data.values.msteams.webhook_url @)
    connectors_with_custom_templates: []
