#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "NetworkPolicy", "metadata":{"name":"prometheus-server"}}), expects=1
---
spec:
  #@overlay/replace, expects=1
  ingress:
  - from: #! allow ingress traffic from all prometheus components
    - podSelector:
        matchLabels:
          app: prometheus
          release: prometheus
    ports:
    - port: 9090
  - from: #! allow ingress traffic from grafana
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
          app.kubernetes.io/instance: grafana
      podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
          app.kubernetes.io/instance: grafana
    ports:
    - port: 9090
  - from: #! allow ingress traffic from ingress pods/controller
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - port: 9090

#@overlay/match by=overlay.subset({"kind": "NetworkPolicy", "metadata":{"name":"prometheus-alertmanager"}}), expects=1
---
spec:
  #@overlay/replace, expects=1
  ingress:
  - from: #! allow ingress traffic from all prometheus components
    - podSelector:
        matchLabels:
          app: prometheus
          release: prometheus
    ports:
    - port: 9093
  - from: #! allow ingress traffic from ingress pods/controller
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - port: 9093
