#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: irvisualizer
  namespace: irvisualizer
spec:
  selector:
    matchLabels:
      app: irvisualizer
      app.service: irvisualizer
      app.service.component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: irvisualizer
        app.service: irvisualizer
        app.service.component: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service.component
                  operator: In
                  values:
                  - frontend
      containers:
      - name: irvisualizer
        image: #@ data.values.irvisualizer.image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        - name: AUTH_PASSWORD
          value: #@ data.values.irvisualizer.auth.password
        - name: AUTH_USERNAME
          value: #@ data.values.irvisualizer.auth.username
        - name: LOGGLY_TOKEN
          value: #@ data.values.loggly_token
        - name: DB_URI
          value: #@ data.values.db_uri
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "64Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircollector
  namespace: irvisualizer
spec:
  selector:
    matchLabels:
      app: irvisualizer
      app.service: ircollector
      app.service.component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: irvisualizer
        app.service: ircollector
        app.service.component: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service
                  operator: In
                  values:
                  - ircollector
                - key: app.service.component
                  operator: In
                  values:
                  - backend
      containers:
      - name: ircollector
        image: #@ data.values.ircollector.image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        - name: AUTH_PASSWORD
          value: #@ data.values.ircollector.auth.password
        - name: AUTH_USERNAME
          value: #@ data.values.ircollector.auth.username
        - name: IR_PASSWORD
          value: #@ data.values.ircollector.iracing_auth.password
        - name: IR_USERNAME
          value: #@ data.values.ircollector.iracing_auth.username
        - name: LOGGLY_TOKEN
          value: #@ data.values.loggly_token
        - name: DB_URI
          value: #@ data.values.db_uri
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /seasons
            port: 8080
            httpHeaders:
            - name: Authorization
              value: #@ data.values.ircollector.auth.header
