#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.irvisualizer.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: irvisualizer
  namespace: #@ data.values.namespace
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("irvisualizer","frontend")
#@ end

#@ if data.values.ircollector.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ircollector
  namespace: #@ data.values.namespace
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("ircollector","backend")
#@ end
