#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
type: Opaque
#@yaml/text-templated-strings
stringData:
  auth.username: "(@= data.values.ircollector.auth.username @)"
  auth.password: "(@= data.values.ircollector.auth.password @)"
  iracing_auth.username: "(@= data.values.ircollector.iracing_auth.username @)"
  iracing_auth.password: "(@= data.values.ircollector.iracing_auth.password @)"
  loggly_token: "(@= data.values.loggly_token @)"
  db_uri: "(@= data.values.db_uri @)"
  basic_auth: "(@= 'Basic ' + base64.encode(data.values.ircollector.auth.username + ':' + data.values.ircollector.auth.password) @)"
