#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

jcio:
  image: "jamesclonk/jcio-frontend:5a967a725f4ac8f0f3209241ed16b091ddcf089f"

moviedb:
  hmac_secret: "${JCIO_HTTP_HMAC_SECRET}"

  frontend:
    image: "jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c"

  backend:
    image: "jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75"
    vcap_services: |
      {
        "user-provided": [
         {
          "binding_name": null,
          "credentials": {
           "maxconns": "5",
           "uri": "${JCIO_MOVIEDB_CONNSTR}"
          },
          "instance_name": "moviedb",
          "label": "user-provided",
          "name": "moviedb",
          "syslog_drain_url": "",
          "tags": [],
          "volume_mounts": []
         }
        ]
      }
