#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ data.values.job + "-config"
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/versioned: ""
#@yaml/text-templated-strings
data:
  images.dat: |
    (@- for image in data.values.images: @)
    (@= image @)
    (@- end @)
