#@ load("@ytt:data", "data")

#@ def jobTemplate():
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: #@ data.values.job
        image: #@ data.values.image
        volumeMounts:
        - name: #@ data.values.job + "-config"
          mountPath: /app/images.dat
          subPath: images.dat
      volumes:
      - name: #@ data.values.job + "-config"
        configMap:
          name: #@ data.values.job + "-config"
      resources:
        requests:
          memory: "64Mi"
          cpu: "25m"
        limits:
          memory: "64Mi"
          cpu: "50m"
#@ end

#@ if data.values.cronjob:
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: #@ data.values.job
  namespace: #@ data.values.namespace
spec:
  schedule: "37 13 * * 0,3"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec: #@ jobTemplate()
#@ end

#@ if data.values.run_job:
---
apiVersion: batch/v1
kind: Job
metadata:
  name: #@ data.values.job
  namespace: #@ data.values.namespace
spec: #@ jobTemplate()
#@ end
