#@ load("@ytt:data", "data")
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: #@ data.values.job
  namespace: #@ data.values.namespace
spec:
  schedule: "37 13 * * 3"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: image-puller
            image: #@ data.values.image
            volumeMounts:
            - name: #@ data.values.job + "-config"
              mountPath: /app/images.dat
              subPath: images.dat
          volumes:
          - name: #@ data.values.job + "-config"
            configMap:
              name: #@ data.values.job + "-config"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          restartPolicy: Never

#! apiVersion: batch/v1
#! kind: Job
#! metadata:
#!   name: #@ data.values.job
#!   namespace: #@ data.values.namespace
#! spec:
#!   template:
#!     spec:
#!       containers:
#!       - name: image-puller
#!         image: #@ data.values.image
#!         volumeMounts:
#!         - name: #@ data.values.job + "-config"
#!           mountPath: /app/images.dat
#!           subPath: images.dat
#!       volumes:
#!       - name: #@ data.values.job + "-config"
#!         configMap:
#!           name: #@ data.values.job + "-config"
#!       resources:
#!         requests:
#!           memory: "64Mi"
#!           cpu: "50m"
#!         limits:
#!           memory: "64Mi"
#!           cpu: "50m"
#!       restartPolicy: Never
