#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata":{"name":"postgres"}}), expects=1
---
metadata:
  #@overlay/replace
  annotations:
    kapp.k14s.io/change-group: "postgres/database"
