#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app + "-database-secret"
  namespace: #@ data.values.namespace
  labels: #@ labels("database")
type: Opaque
stringData:
  POSTGRES_DB: #@ data.values.postgres.database.name
  POSTGRES_USER: #@ data.values.postgres.database.user
  POSTGRES_PASSWORD: #@ data.values.postgres.database.password
  PGDATA: /var/lib/postgresql/data/pgdata
