#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "PodSecurityPolicy", "metadata":{"name":"postgres"}}), expects=1
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    #@overlay/match missing_ok=True
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    #@overlay/match missing_ok=True
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    #@overlay/match missing_ok=True
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  #@overlay/match missing_ok=True
  allowPrivilegeEscalation: false

#@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata":{"name":"postgres"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"postgres"}), expects=1
      - name: postgres
        #@overlay/match missing_ok=True
        securityContext:
          #@overlay/match missing_ok=True
          privileged: false
          #@overlay/match missing_ok=True
          allowPrivilegeEscalation: false
      #@overlay/match by=overlay.subset({"name":"metrics"}), expects=1
      - name: metrics
        #@overlay/match missing_ok=True
        securityContext:
          #@overlay/match missing_ok=True
          privileged: false
          #@overlay/match missing_ok=True
          allowPrivilegeEscalation: false
