#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

replicas: 1
image: "jamesclonk/cf-env:89d20c44e3d6b1a4e0c0502e9d1f5bc908e81264"

enable_pod_security_policy: true
