apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcio-frontend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: www
      app.service.component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: jcio
        app.service: www
        app.service.component: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jcio
                - key: app.service
                  operator: In
                  values:
                  - www
                - key: app.service.component
                  operator: In
                  values:
                  - frontend
      containers:
      - name: jcio-frontend
        image: jamesclonk/jcio-frontend:1c8512cf2ceeb3d0c6cba0784c6f574229d0fbec
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: JCIO_ENV
          value: production
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb-frontend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: moviedb
      app.service.component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: jcio
        app.service: moviedb
        app.service.component: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jcio
                - key: app.service
                  operator: In
                  values:
                  - moviedb
                - key: app.service.component
                  operator: In
                  values:
                  - frontend
      containers:
      - name: moviedb-frontend
        image: jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c
        ports:
        - containerPort: 3007
        env:
        - name: PORT
          value: "3007"
        - name: JCIO_ENV
          value: production
        - name: JCIO_MOVIEDB_BACKEND
          value: http://moviedb-backend.jcio:4007
        - name: JCIO_HTTP_HMAC_SECRET
          value: ${JCIO_HTTP_HMAC_SECRET}
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3007
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 3007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb-backend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: moviedb
      app.service.component: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: jcio
        app.service: moviedb
        app.service.component: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jcio
                - key: app.service
                  operator: In
                  values:
                  - moviedb
                - key: app.service.component
                  operator: In
                  values:
                  - backend
      containers:
      - name: moviedb-backend
        image: jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75
        ports:
        - containerPort: 4007
        env:
        - name: PORT
          value: "4007"
        - name: JCIO_ENV
          value: production
        - name: JCIO_HTTP_HMAC_SECRET
          value: ${JCIO_HTTP_HMAC_SECRET}
        - name: JCIO_DATABASE_TYPE
          value: postgres
        - name: VCAP_SERVICES
          value: |
            {
              "user-provided": [
               {
                "binding_name": null,
                "credentials": {
                 "maxconns": "5",
                 "uri": "${JCIO_MOVIEDB_CONNSTR}"
                },
                "instance_name": "moviedb",
                "label": "user-provided",
                "name": "moviedb",
                "syslog_drain_url": "",
                "tags": [],
                "volume_mounts": []
               }
              ]
            }
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 4007
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 4007
