apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcio-frontend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: www
      app.service.component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: jcio
        app.service: www
        app.service.component: frontend
    spec:
      containers:
      - name: jcio-frontend
        image: jamesclonk/jcio-frontend:9fc1aaca127b7d049df8a06a29519b26fd64d5f0
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: JCIO_ENV
          value: production
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb-frontend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: moviedb
      app.service.component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: jcio
        app.service: moviedb
        app.service.component: frontend
    spec:
      containers:
      - name: moviedb-frontend
        image: jamesclonk/moviedb-frontend:87286a8dd8d0ff6fb9108880b51887854ad0872c
        ports:
        - containerPort: 3007
        env:
        - name: PORT
          value: "3007"
        - name: JCIO_ENV
          value: production
        - name: JCIO_MOVIEDB_BACKEND
          value: https://moviedb-backend.${KUBE_DOMAIN}
        - name: JCIO_HTTP_HMAC_SECRET
          value: ${JCIO_HTTP_HMAC_SECRET}
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviedb-backend
spec:
  selector:
    matchLabels:
      app: jcio
      app.service: moviedb
      app.service.component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: jcio
        app.service: moviedb
        app.service.component: backend
    spec:
      containers:
      - name: moviedb-backend
        image: jamesclonk/moviedb-backend:6abf341bd5f1d050e43ac34be3f56b0f72e4af75
        ports:
        - containerPort: 4007
        env:
        - name: PORT
          value: "4007"
        - name: JCIO_ENV
          value: production
        - name: JCIO_HTTP_HMAC_SECRET
          value: ${JCIO_HTTP_HMAC_SECRET}
        - name: JCIO_DATABASE_TYPE
          value: postgres
        - name: VCAP_SERVICES
          value: |
            {
              "user-provided": [
               {
                "binding_name": null,
                "credentials": {
                 "maxconns": "5",
                 "uri": "${JCIO_MOVIEDB_CONNSTR}"
                },
                "instance_name": "moviedb",
                "label": "user-provided",
                "name": "moviedb",
                "syslog_drain_url": "",
                "tags": [],
                "volume_mounts": []
               }
              ]
            }
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 4007
