version: 2.1

orbs:
  kube-orb: circleci/kubernetes@0.11.0

jobs:
  build:
    docker:
    - image: 'cimg/base:stable'
    steps:
    - checkout
    - kube-orb/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
    - run: make setup
    - run: make target-prod
    - run: make deploy
