#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

ingress:
  auth: "${PROMETHEUS_BASIC_AUTH}"
  username: "${PROMETHEUS_BASIC_AUTH_USERNAME}"
  password: "${PROMETHEUS_BASIC_AUTH_PASSWORD}"
