#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

ingress:
  auth: "${PROMETHEUS_BASIC_AUTH}"
  username: "${PROMETHEUS_BASIC_AUTH_USERNAME}"
  password: "${PROMETHEUS_BASIC_AUTH_PASSWORD}"

backman:
  username: "${BACKMAN_USERNAME}"
  password: "${BACKMAN_PASSWORD}"

alertmanager:
  email_from: "${PROMETHEUS_EMAIL_FROM}"
  email_to: "${PROMETHEUS_EMAIL_TO}"
  email_password: "${PROMETHEUS_EMAIL_PASSWORD}"
  slack_api_url: "${PROMETHEUS_SLACK_WEBHOOK}"
