#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

backman:
  replicas: 1
  image: "jamesclonk/backman:1.15.0"

  enable_network_policy: true
  enable_pod_security_policy: true

  username: "${BACKMAN_USERNAME}"
  password: "${BACKMAN_PASSWORD}"

  s3:
    host: "${BACKMAN_S3_HOST}"
    key: "${BACKMAN_S3_KEY}"
    secret: "${BACKMAN_S3_SECRET}"

  postgres:
  - name: irvisualizer_db
    database: irvisualizer
    uri: "postgres://${IR_VISUALIZER_DB_USERNAME}:${IR_VISUALIZER_DB_PASSWORD}@${IR_VISUALIZER_DB_HOST}/${IR_VISUALIZER_DB_NAME}?sslmode=require"
  - name: home_info_db
    database: home_info
    uri: "postgres://${HOME_INFO_DB_USERNAME}:${HOME_INFO_DB_PASSWORD}@${HOME_INFO_DB_HOST}/${HOME_INFO_DB_NAME}?sslmode=require"
  - name: movie_db
    database: moviedb
    uri: "postgres://${JCIO_MOVIEDB_USERNAME}:${JCIO_MOVIEDB_PASSWORD}@${JCIO_MOVIEDB_HOST}/${JCIO_MOVIEDB_NAME}?sslmode=require"
