#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

backman:
  replicas: 1
  image: "jamesclonk/backman:1.15.0"

  username: "${BACKMAN_USERNAME}"
  password: "${BACKMAN_PASSWORD}"

  s3:
    host: "${BACKMAN_S3_HOST}"
    key: "${BACKMAN_S3_KEY}"
    secret: "${BACKMAN_S3_SECRET}"

  postgres:
  - name: irvisualizer_db
    database: irvisualizer
    uri: "${IR_VISUALIZER_DB_URI}"
  - name: home_info_db
    database: home_info
    uri: "${HOME_INFO_DB_URI}"
  - name: movie_db
    database: moviedb
    uri: "${JCIO_MOVIEDB_CONNSTR}"
