#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

grafana:
  enable_network_policy: true
  username: ${GRAFANA_USERNAME}
  password: ${GRAFANA_PASSWORD}

ingress:
  auth: "${GRAFANA_BASIC_AUTH}"
  username: "${GRAFANA_BASIC_AUTH_USERNAME}"
  password: "${GRAFANA_BASIC_AUTH_PASSWORD}"
