apiVersion: apps/v1
kind: Deployment
metadata:
  name: irvisualizer
spec:
  selector:
    matchLabels:
      app: irvisualizer
      app.service: irvisualizer
      app.service.component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: irvisualizer
        app.service: irvisualizer
        app.service.component: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service.component
                  operator: In
                  values:
                  - frontend
      containers:
      - name: irvisualizer
        image: jamesclonk/irvisualizer:6ccd343b9f3cb7e995421c007f28885fbd8eb898
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        - name: AUTH_PASSWORD
          value: "${IR_VISUALIZER_AUTH_PASSWORD}"
        - name: AUTH_USERNAME
          value: "${IR_VISUALIZER_AUTH_USERNAME}"
        - name: LOGGLY_TOKEN
          value: "${IR_VISUALIZER_LOGGLY_TOKEN}"
        - name: DB_URI
          value: "${IR_VISUALIZER_DB_URI}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "64Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircollector
spec:
  selector:
    matchLabels:
      app: irvisualizer
      app.service: ircollector
      app.service.component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: irvisualizer
        app.service: ircollector
        app.service.component: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - irvisualizer
                - key: app.service
                  operator: In
                  values:
                  - ircollector
                - key: app.service.component
                  operator: In
                  values:
                  - backend
      containers:
      - name: ircollector
        image: jamesclonk/ircollector:20e3d8ba9e6f81fa728c2c3bd82d417f31c154cf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "debug"
        - name: AUTH_PASSWORD
          value: "${IR_VISUALIZER_AUTH_PASSWORD}"
        - name: AUTH_USERNAME
          value: "${IR_VISUALIZER_AUTH_USERNAME}"
        - name: IR_PASSWORD
          value: "${IR_VISUALIZER_IR_PASSWORD}"
        - name: IR_USERNAME
          value: "${IR_VISUALIZER_IR_USERNAME}"
        - name: LOGGLY_TOKEN
          value: "${IR_VISUALIZER_LOGGLY_TOKEN}"
        - name: DB_URI
          value: "${IR_VISUALIZER_DB_URI}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /seasons
            port: 8080
            httpHeaders:
            - name: Authorization
              value: ${IR_VISUALIZER_AUTH_HEADER}
