#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels", "podAntiAffinity")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app + "-dashboard"
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels: #@ labels("dashboard")
  replicas: #@ data.values.home_info.replicas
  template:
    metadata:
      labels: #@ labels("dashboard")
    spec:
      affinity: #@ podAntiAffinity("dashboard")
      containers:
      - name: home-info-dashboard
        image: #@ data.values.home_info.image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: HOME_INFO_DB_URI
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: home_info.db_uri
        - name: AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: auth.username
        - name: AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: auth.password
        - name: CONFIG_BEDROOM_HUMIDITY_SENSOR_ID
          value: "5"
        - name: CONFIG_BEDROOM_TEMPERATURE_SENSOR_ID
          value: "4"
        - name: CONFIG_FORECAST_TEMPERATURE_SENSOR_ID
          value: "3"
        - name: CONFIG_HOME_OFFICE_HUMIDITY_SENSOR_ID
          value: "7"
        - name: CONFIG_HOME_OFFICE_TEMPERATURE_SENSOR_ID
          value: "6"
        - name: CONFIG_LIVING_ROOM_HUMIDITY_SENSOR_ID
          value: "2"
        - name: CONFIG_LIVING_ROOM_TEMPERATURE_SENSOR_ID
          value: "1"
        - name: DEFAULT_CANTON
          value: "Bern"
        - name: DEFAULT_CITY
          value: "Bern"
        - name: SLACK_CHANNEL
          value: "USER_Fabio"
        - name: SLACK_DEBUG
          value: "false"
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: slack.token
        - name: TELEBOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: telebot.username
        - name: TELEBOT_DEBUG
          value: "false"
        - name: TELEBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: telebot.token
        - name: TZ
          value: "Europe/Zurich"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "150m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
