#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.home_info.replicas > 1:
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: #@ data.values.app + "-dashboard"
  namespace: #@ data.values.namespace
spec:
  minAvailable: 50%
  selector:
    matchLabels: #@ labels("dashboard")
#@ end
