#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
type: Opaque
#@yaml/text-templated-strings
stringData:
  home_info.db_uri: "(@= data.values.home_info.db_uri @)"
  auth.username: "(@= data.values.home_info.auth.username @)"
  auth.password: "(@= data.values.home_info.auth.password @)"
  slack.token: "(@= data.values.home_info.slack.token @)"
  telebot.username: "(@= data.values.home_info.telebot.username @)"
  telebot.token: "(@= data.values.home_info.telebot.token @)"
