#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  HOME_INFO_DB_URI: #@ data.values.home_info.db_uri
  AUTH_USERNAME: #@ data.values.home_info.auth.username
  AUTH_PASSWORD: #@ data.values.home_info.auth.password
  SLACK_CHANNEL: "USER_Fabio"
  SLACK_TOKEN: #@ data.values.home_info.slack.token
  SLACK_DEBUG: "false"
  TELEBOT_USERNAME: #@ data.values.home_info.telebot.username
  TELEBOT_TOKEN: #@ data.values.home_info.telebot.token
  TELEBOT_DEBUG: "false"
  CONFIG_BEDROOM_HUMIDITY_SENSOR_ID: "5"
  CONFIG_BEDROOM_TEMPERATURE_SENSOR_ID: "4"
  CONFIG_FORECAST_TEMPERATURE_SENSOR_ID: "3"
  CONFIG_HOME_OFFICE_HUMIDITY_SENSOR_ID: "7"
  CONFIG_HOME_OFFICE_TEMPERATURE_SENSOR_ID: "6"
  CONFIG_LIVING_ROOM_HUMIDITY_SENSOR_ID: "2"
  CONFIG_LIVING_ROOM_TEMPERATURE_SENSOR_ID: "1"
