apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kuard
spec:
  rules:
  - host: kuard.127.0.0.1.xip.io
    http:
      paths:
      - backend:
          serviceName: kuard
          servicePort: 80
