#@data/values
---
app: postgres
namespace: postgres

postgres:
  image: "jamesclonk/postgres-k8s:latest"

  memory_in_mb: 256
  disk_in_gb: 1
  persistent_volume: true

  database:
    port: 5432
    name: test-db
    user: test-user
    password: test-password

pgadmin:
  image: "dpage/pgadmin4@sha256:e4a446a0f4b54465790e12ee5a684f1c21d5aeb6d3a6e4f8448c0ee4a6c2bce4" #! dpage/pgadmin4:4.25

  enabled: false
  auth:
    user: pgadmin-user
    password: pgadmin-password

pgweb:
  image: "sosedoff/pgweb@sha256:fcb0acce73e0382249e268c4616d83f9ff6e5dda467904905fd24317ec56712a" #! sosedoff/pgweb:0.11.6

  enabled: true
  auth:
    user: pgweb-user
    password: pgweb-password
