#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

home_info:
  image: "jamesclonk/home-info-dashboard:29132cf31dd416c2b0cf7d68ab1bcace74f72178"

  db_uri: "${HOME_INFO_DB_URI}"

  auth:
    username: "${HOME_INFO_AUTH_USERNAME}"
    password: "${HOME_INFO_AUTH_PASSWORD}"
  slack:
    token: "${HOME_INFO_SLACK_TOKEN}"
  telebot:
    username: "${HOME_INFO_TELEBOT_USERNAME}"
    token: "${HOME_INFO_TELEBOT_TOKEN}"
