#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

home_info:
  replicas: 2
  image: "jamesclonk/home-info-dashboard:f146a89557db4d22635f96bbea62ffc256a2d3d6"

  enable_network_policy: true
  enable_pod_security_policy: false

  db_uri: "postgres://${HOME_INFO_DB_USERNAME}:${HOME_INFO_DB_PASSWORD}@${HOME_INFO_DB_HOST}/${HOME_INFO_DB_NAME}?sslmode=require"

  auth:
    username: "${HOME_INFO_AUTH_USERNAME}"
    password: "${HOME_INFO_AUTH_PASSWORD}"
  slack:
    token: "${HOME_INFO_SLACK_TOKEN}"
  telebot:
    username: "${HOME_INFO_TELEBOT_USERNAME}"
    token: "${HOME_INFO_TELEBOT_TOKEN}"
