#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

db_uri: "${IR_VISUALIZER_DB_URI}"
loggly_token: "${IR_VISUALIZER_LOGGLY_TOKEN}"

irvisualizer:
  replicas: 2
  image: "jamesclonk/irvisualizer:c4631594422aeeb58dbbd84a939e9b7f741c9f1f"

  auth:
    username: "${IR_VISUALIZER_AUTH_USERNAME}"
    password: "${IR_VISUALIZER_AUTH_PASSWORD}"

ircollector:
  replicas: 1
  image: "jamesclonk/ircollector:24ceeaf90147f1757777e8fe7fde54074191f2bf"

  auth:
    username: "${IR_VISUALIZER_AUTH_USERNAME}"
    password: "${IR_VISUALIZER_AUTH_PASSWORD}"

  iracing_auth:
    username: "${IR_VISUALIZER_IR_USERNAME}"
    password: "${IR_VISUALIZER_IR_PASSWORD}"
