#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

enable_network_policy: true

db_uri: "postgres://${IR_VISUALIZER_DB_USERNAME}:${IR_VISUALIZER_DB_PASSWORD}@${IR_VISUALIZER_DB_HOST}/${IR_VISUALIZER_DB_NAME}?sslmode=require"
loggly_token: "${IR_VISUALIZER_LOGGLY_TOKEN}"

irvisualizer:
  replicas: 2
  image: "jamesclonk/irvisualizer:387a0f13eb7e9863d5ebe9b709c7e8850cd49c72"

  auth:
    username: "${IR_VISUALIZER_AUTH_USERNAME}"
    password: "${IR_VISUALIZER_AUTH_PASSWORD}"

ircollector:
  replicas: 1
  image: "jamesclonk/ircollector:d41f35a96ee8cc387df96af06684021687fbcaae"

  auth:
    username: "${IR_VISUALIZER_AUTH_USERNAME}"
    password: "${IR_VISUALIZER_AUTH_PASSWORD}"

  iracing_auth:
    username: "${IR_VISUALIZER_IR_USERNAME}"
    password: "${IR_VISUALIZER_IR_PASSWORD}"
