#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-env
  namespace: cf-env
spec:
  selector:
    matchLabels:
      app: cf-env
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cf-env
    spec:
      containers:
      - name: cf-env
        image: #@ data.values.image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "32Mi"
            cpu: "5m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
