#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels", "podAntiAffinity")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
spec:
  selector:
    matchLabels: #@ labels("backman","gui")
  replicas: #@ data.values.backman.replicas
  template:
    metadata:
      labels: #@ labels("backman","gui")
    spec:
      affinity: #@ podAntiAffinity("backman","gui")
      containers:
      - name: backman
        image: #@ data.values.backman.image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: TZ
          value: "Europe/Zurich"
        - name: BACKMAN_USERNAME
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: username
        - name: BACKMAN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: password
        - name: PROBE_AUTHORIZATION
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: basic_auth
        - name: BACKMAN_CONFIG
          value: |
            {
              "log_level": "debug",
              "s3": {
                "service_label": "user-provided",
                "service_name": "backman-storage",
                "bucket_name": "backman-storage"
              }
            }
        - name: VCAP_APPLICATION
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: vcap_application.json
        - name: VCAP_SERVICES
          valueFrom:
            secretKeyRef:
              name: #@ data.values.app
              key: vcap_services.json
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'curl --fail http://localhost:8080/metrics --header "Authorization: ${PROBE_AUTHORIZATION}"'
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - bash
            - -c
            - 'curl --fail http://localhost:8080/api/v1/states --header "Authorization: ${PROBE_AUTHORIZATION}"'
