#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels", "podAntiAffinity")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
  labels: #@ labels("backman","gui")
spec:
  selector:
    matchLabels: #@ labels("backman","gui")
  replicas: #@ data.values.backman.replicas
  template:
    metadata:
      labels: #@ labels("backman","gui")
    spec:
      serviceAccountName: #@ data.values.app
      securityContext:
        runAsUser: 1007
        runAsGroup: 1007
        fsGroup: 1007
      affinity: #@ podAntiAffinity("backman","gui")
      containers:
      - name: backman
        image: #@ data.values.backman.image
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: TZ
          value: "Europe/Zurich"
        envFrom:
        - secretRef:
            name: #@ data.values.app
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - 'curl --fail http://localhost:8080/metrics --header "Authorization: ${PROBE_AUTHORIZATION}"'
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - bash
            - -c
            - 'curl --fail http://localhost:8080/api/v1/states --header "Authorization: ${PROBE_AUTHORIZATION}"'
