#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
type: Opaque
#@yaml/text-templated-strings
stringData:
  hmac_secret: "(@= data.values.moviedb.hmac_secret @)"
  vcap_services.json: |
    {
      "user-provided": [
       {
        "credentials": {
         "uri": "(@= data.values.moviedb.backend.db_uri @)"
        },
        "label": "user-provided",
        "name": "moviedb"
       }
      ]
    }
