apiVersion: v1
kind: Service
metadata:
  name: jcio-frontend
  namespace: jcio
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: jcio
    app.service: www
    app.service.component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: moviedb-frontend
  namespace: jcio
spec:
  ports:
  - port: 3007
    targetPort: 3007
  selector:
    app: jcio
    app.service: moviedb
    app.service.component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: moviedb-backend
  namespace: jcio
spec:
  ports:
  - port: 4007
    targetPort: 4007
  selector:
    app: jcio
    app.service: moviedb
    app.service.component: backend
