apiVersion: v1
kind: Namespace
metadata:
  name: kuard
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: kuard
type: Opaque
data:
  auth: ${BASIC_AUTH}
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: kuard
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kuard
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: kuard
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  rules:
  - host: kuard.51.15.242.160.xip.io
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
        ports:
        - containerPort: 8080
