#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app + "-basic-auth"
  namespace: #@ data.values.namespace
  labels: #@ labels("basic-auth")
type: Opaque
data:
  #@ if len(data.values.ingress.auth) == 0:
  #@  assert.fail("data.values.ingress.auth cannot be empty")
  #@ end
  auth: #@ data.values.ingress.auth
stringData:
  #@ if len(data.values.ingress.username) == 0:
  #@  assert.fail("data.values.ingress.username cannot be empty")
  #@ end
  AUTH_USER: #@ data.values.ingress.username
  #@ if len(data.values.ingress.password) == 0:
  #@  assert.fail("data.values.ingress.password cannot be empty")
  #@ end
  AUTH_PASS: #@ data.values.ingress.password

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.app
  namespace: #@ data.values.namespace
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@yaml/text-templated-strings
  config.xml: |
    <configuration version="32">
        <gui enabled="true" tls="false" debugging="false">
            <address>0.0.0.0:8384</address>
            <apikey>(@= data.values.ingress.username @)-(@= data.values.ingress.password @)</apikey>
            <theme>default</theme>
        </gui>
        <options>
            <listenAddress>tcp://0.0.0.0:22000</listenAddress>
            <listenAddress>quic://0.0.0.0:22000</listenAddress>
            <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>
            <globalAnnounceEnabled>false</globalAnnounceEnabled>
            <localAnnounceEnabled>false</localAnnounceEnabled>
            <reconnectionIntervalS>60</reconnectionIntervalS>
            <relaysEnabled>false</relaysEnabled>
            <startBrowser>false</startBrowser>
            <natEnabled>false</natEnabled>
            <urAccepted>-1</urAccepted>
            <urPostInsecurely>false</urPostInsecurely>
            <urInitialDelayS>1800</urInitialDelayS>
            <restartOnWakeup>true</restartOnWakeup>
            <autoUpgradeIntervalH>0</autoUpgradeIntervalH>
            <stunKeepaliveSeconds>0</stunKeepaliveSeconds>
            <defaultFolderPath></defaultFolderPath>
        </options>
        <folder id="default" label="Default Folder" path="/var/syncthing/Sync" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
            <filesystemType>basic</filesystemType>
            <device id="IPP5OG3-DWOYFSP-7LQW3YT-HEAGEKF-V4H2SPS-4AYY7W5-O5ZSQDE-SU4TOQO" introducedBy=""></device>
            <minDiskFree unit="%">2</minDiskFree>
            <versioning></versioning>
            <copiers>0</copiers>
            <pullerMaxPendingKiB>0</pullerMaxPendingKiB>
            <hashers>0</hashers>
            <order>random</order>
            <ignoreDelete>false</ignoreDelete>
            <scanProgressIntervalS>0</scanProgressIntervalS>
            <pullerPauseS>0</pullerPauseS>
            <maxConflicts>-1</maxConflicts>
            <disableSparseFiles>false</disableSparseFiles>
            <disableTempIndexes>false</disableTempIndexes>
            <paused>false</paused>
            <weakHashThresholdPct>25</weakHashThresholdPct>
            <markerName>.stfolder</markerName>
            <copyOwnershipFromParent>false</copyOwnershipFromParent>
            <modTimeWindowS>0</modTimeWindowS>
            <maxConcurrentWrites>2</maxConcurrentWrites>
            <disableFsync>false</disableFsync>
            <blockPullOrder>standard</blockPullOrder>
            <copyRangeMethod>standard</copyRangeMethod>
            <caseSensitiveFS>false</caseSensitiveFS>
            <junctionsAsDirs>false</junctionsAsDirs>
        </folder>
        <device id="IPP5OG3-DWOYFSP-7LQW3YT-HEAGEKF-V4H2SPS-4AYY7W5-O5ZSQDE-SU4TOQO" name="kubernetes" compression="metadata" introducer="false" skipIntroductionRemovals="false" introducedBy="">
            <address>dynamic</address>
            <paused>false</paused>
            <autoAcceptFolders>false</autoAcceptFolders>
            <maxSendKbps>0</maxSendKbps>
            <maxRecvKbps>0</maxRecvKbps>
            <maxRequestKiB>0</maxRequestKiB>
        </device>
    </configuration>

#!            <user>(@= data.values.ingress.username @)</user>
#!            <password>(@= data.values.ingress.password @)</password>

#!    <options>
#!        <listenAddress>default</listenAddress>
#!        <globalAnnounceServer>default</globalAnnounceServer>
#!        <globalAnnounceEnabled>true</globalAnnounceEnabled>
#!        <localAnnounceEnabled>true</localAnnounceEnabled>
#!        <localAnnouncePort>21027</localAnnouncePort>
#!        <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr>
#!        <maxSendKbps>0</maxSendKbps>
#!        <maxRecvKbps>0</maxRecvKbps>
#!        <reconnectionIntervalS>60</reconnectionIntervalS>
#!        <relaysEnabled>true</relaysEnabled>
#!        <relayReconnectIntervalM>10</relayReconnectIntervalM>
#!        <startBrowser>true</startBrowser>
#!        <natEnabled>true</natEnabled>
#!        <natLeaseMinutes>60</natLeaseMinutes>
#!        <natRenewalMinutes>30</natRenewalMinutes>
#!        <natTimeoutSeconds>10</natTimeoutSeconds>
#!        <urAccepted>0</urAccepted>
#!        <urSeen>0</urSeen>
#!        <urUniqueID></urUniqueID>
#!        <urURL>https://data.syncthing.net/newdata</urURL>
#!        <urPostInsecurely>false</urPostInsecurely>
#!        <urInitialDelayS>1800</urInitialDelayS>
#!        <restartOnWakeup>true</restartOnWakeup>
#!        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
#!        <upgradeToPreReleases>false</upgradeToPreReleases>
#!        <keepTemporariesH>24</keepTemporariesH>
#!        <cacheIgnoredFiles>false</cacheIgnoredFiles>
#!        <progressUpdateIntervalS>5</progressUpdateIntervalS>
#!        <limitBandwidthInLan>false</limitBandwidthInLan>
#!        <minHomeDiskFree unit="%">1</minHomeDiskFree>
#!        <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL>
#!        <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect>
#!        <tempIndexMinBlocks>10</tempIndexMinBlocks>
#!        <unackedNotificationID>authenticationUserAndPassword</unackedNotificationID>
#!        <trafficClass>0</trafficClass>
#!        <defaultFolderPath>~</defaultFolderPath>
#!        <setLowPriority>true</setLowPriority>
#!        <maxFolderConcurrency>0</maxFolderConcurrency>
#!        <crashReportingURL>https://crash.syncthing.net/newcrash</crashReportingURL>
#!        <crashReportingEnabled>true</crashReportingEnabled>
#!        <stunKeepaliveStartS>180</stunKeepaliveStartS>
#!        <stunKeepaliveMinS>20</stunKeepaliveMinS>
#!        <stunServer>default</stunServer>
#!        <databaseTuning>auto</databaseTuning>
#!        <maxConcurrentIncomingRequestKiB>0</maxConcurrentIncomingRequestKiB>
#!    </options>

#!    <configuration version="30">
#!        <folder id="default" label="Default Folder" path="/Users/jb/Sync/" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
#!            <filesystemType>basic</filesystemType>
#!            <device id="3LT2GA5-CQI4XJM-WTZ264P-MLOGMHL-MCRLDNT-MZV4RD3-KA745CL-OGAERQZ"></device>
#!            <minDiskFree unit="%">1</minDiskFree>
#!            <versioning></versioning>
#!            <copiers>0</copiers>
#!            <pullerMaxPendingKiB>0</pullerMaxPendingKiB>
#!            <hashers>0</hashers>
#!            <order>random</order>
#!            <ignoreDelete>false</ignoreDelete>
#!            <scanProgressIntervalS>0</scanProgressIntervalS>
#!            <pullerPauseS>0</pullerPauseS>
#!            <maxConflicts>-1</maxConflicts>
#!            <disableSparseFiles>false</disableSparseFiles>
#!            <disableTempIndexes>false</disableTempIndexes>
#!            <paused>false</paused>
#!            <weakHashThresholdPct>25</weakHashThresholdPct>
#!            <markerName>.stfolder</markerName>
#!            <copyOwnershipFromParent>false</copyOwnershipFromParent>
#!            <modTimeWindowS>0</modTimeWindowS>
#!            <maxConcurrentWrites>2</maxConcurrentWrites>
#!            <disableFsync>false</disableFsync>
#!            <blockPullOrder>standard</blockPullOrder>
#!            <copyRangeMethod>standard</copyRangeMethod>
#!        </folder>
#!        <device id="3LT2GA5-CQI4XJM-WTZ264P-MLOGMHL-MCRLDNT-MZV4RD3-KA745CL-OGAERQZ" name="syno" compression="metadata" introducer="false" skipIntroductionRemovals="false" introducedBy="">
#!            <address>dynamic</address>
#!            <paused>false</paused>
#!            <autoAcceptFolders>false</autoAcceptFolders>
#!            <maxSendKbps>0</maxSendKbps>
#!            <maxRecvKbps>0</maxRecvKbps>
#!            <maxRequestKiB>0</maxRequestKiB>
#!        </device>
#!        <options>
#!            <listenAddress>tcp://0.0.0.0:8384</listenAddress>
#!            <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>
#!            <globalAnnounceServer>default</globalAnnounceServer>
#!            <globalAnnounceEnabled>true</globalAnnounceEnabled>
#!            <localAnnounceEnabled>true</localAnnounceEnabled>
#!            <localAnnouncePort>21027</localAnnouncePort>
#!            <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr>
#!            <maxSendKbps>0</maxSendKbps>
#!            <maxRecvKbps>0</maxRecvKbps>
#!            <reconnectionIntervalS>60</reconnectionIntervalS>
#!            <relaysEnabled>true</relaysEnabled>
#!            <relayReconnectIntervalM>10</relayReconnectIntervalM>
#!            <startBrowser>true</startBrowser>
#!            <natEnabled>true</natEnabled>
#!            <natLeaseMinutes>60</natLeaseMinutes>
#!            <natRenewalMinutes>30</natRenewalMinutes>
#!            <natTimeoutSeconds>10</natTimeoutSeconds>
#!            <urAccepted>0</urAccepted>
#!            <urSeen>0</urSeen>
#!            <urUniqueID></urUniqueID>
#!            <urURL>https://data.syncthing.net/newdata</urURL>
#!            <urPostInsecurely>false</urPostInsecurely>
#!            <urInitialDelayS>1800</urInitialDelayS>
#!            <restartOnWakeup>true</restartOnWakeup>
#!            <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
#!            <upgradeToPreReleases>false</upgradeToPreReleases>
#!            <keepTemporariesH>24</keepTemporariesH>
#!            <cacheIgnoredFiles>false</cacheIgnoredFiles>
#!            <progressUpdateIntervalS>5</progressUpdateIntervalS>
#!            <limitBandwidthInLan>false</limitBandwidthInLan>
#!            <minHomeDiskFree unit="%">1</minHomeDiskFree>
#!            <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL>
#!            <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect>
#!            <tempIndexMinBlocks>10</tempIndexMinBlocks>
#!            <trafficClass>0</trafficClass>
#!            <defaultFolderPath>~</defaultFolderPath>
#!            <setLowPriority>true</setLowPriority>
#!            <maxFolderConcurrency>0</maxFolderConcurrency>
#!            <crashReportingURL>https://crash.syncthing.net/newcrash</crashReportingURL>
#!            <crashReportingEnabled>true</crashReportingEnabled>
#!            <stunKeepaliveStartS>180</stunKeepaliveStartS>
#!            <stunKeepaliveMinS>20</stunKeepaliveMinS>
#!            <stunServer>default</stunServer>
#!            <databaseTuning>auto</databaseTuning>
#!            <maxConcurrentIncomingRequestKiB>0</maxConcurrentIncomingRequestKiB>
#!        </options>
#!    </configuration>