#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: #@ data.values.kuard.image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "16Mi"
            cpu: "5m"
          limits:
            memory: "32Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
      # doesnt work with only 1 node..
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - topologyKey: "kubernetes.io/hostname"
      #       labelSelector:
      #         matchExpressions:
      #         - key: "app"
      #           operator: In
      #           values:
      #           - kuard
