#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

#@overlay/match missing_ok=True
domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

postgres:
  memory_in_mb: 512
  disk_in_gb: 5
  persistent_volume: true

  database:
    password: "${POSTGRES_DB_PASSWORD}"

  additional_databases:
  #@overlay/replace
  - name: "${IR_VISUALIZER_DB_NAME}"
    user: "${IR_VISUALIZER_DB_USERNAME}"
    password: "${IR_VISUALIZER_DB_PASSWORD}"
  - name: "${HOME_INFO_DB_NAME}"
    user: "${HOME_INFO_DB_USERNAME}"
    password: "${HOME_INFO_DB_PASSWORD}"
  - name: "${JCIO_MOVIEDB_NAME}"
    user: "${JCIO_MOVIEDB_USERNAME}"
    password: "${JCIO_MOVIEDB_PASSWORD}"

pgadmin:
  enabled: true
  auth:
    user: "${POSTGRES_PGADMIN_USERNAME}"
    password: "${POSTGRES_PGADMIN_PASSWORD}"

pgweb:
  enabled: true
  auth:
    user: "${POSTGRES_PGWEB_USERNAME}"
    password: "${POSTGRES_PGWEB_PASSWORD}"
