#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

#@overlay/match missing_ok=True
domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

postgres:
  memory_in_mb: 128
  disk_in_gb: 1
  persistent_volume: false

  database:
    port: 5432
    name: test-db
    user: test-user
    password: test-password

pgadmin:
  enabled: false

pgweb:
  enabled: true
  auth:
    user: pgweb-user
    password: pgweb-password
