#@data/values
---
app: ${KUBE_APP_NAME}
namespace: ${KUBE_APP_NAME}

#@overlay/match missing_ok=True
domains:
- ${KUBE_DOMAIN_ALPHA}
- ${KUBE_DOMAIN_BETA}

postgres:
  memory_in_mb: 128
  disk_in_gb: 1
  persistent_volume: false

  database:
    port: 5432
    name: postgres
    user: "${POSTGRES_DB_USER}"
    password: "${POSTGRES_DB_PASSWORD}"

  additional_databases:
  - name: "${IR_VISUALIZER_DB_NAME}"
    user: "${IR_VISUALIZER_DB_USER}"
    password: "${IR_VISUALIZER_DB_PASSWORD}"
  - name: "${HOME_INFO_DB_NAME}"
    user: "${HOME_INFO_DB_USER}"
    password: "${HOME_INFO_DB_PASSWORD}"
  - name: "${JCIO_MOVIEDB_NAME}"
    user: "${JCIO_MOVIEDB_USER}"
    password: "${JCIO_MOVIEDB_PASSWORD}"

pgadmin:
  enabled: false

pgweb:
  enabled: true
  auth:
    user: "${POSTGRES_PGWEB_USER}"
    password: "${POSTGRES_PGWEB_PASSWORD}"
