#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.job + "-secret"
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  gitlab-token: #@ data.values.gitlab_token
