#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.job + "-secret"
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  gitlab-token: #@ data.values.gitlab_token
